# System prompts

RAG_SYSTEM_PROMPT = "Try to answer using the provided context, and mention which source and page the answer comes from. If the answer is not in the context, you may answer using your own general knowledge, but you MUST explicitly and clearly state that you are doing so because the information was not found in the provided documents."

RAG_FOLLOWUP_SYSTEM_PROMPT = "Try to answer using the provided context, and mention which source and page the answer comes from. If the answer is not in the context, you may answer using your own general knowledge, but you MUST explicitly and clearly state that you are doing so because the information was not found in the provided documents. The conversation so far is provided below. Use it to understand follow-up questions like 'tell me more' or 'what about the second point?'. Always prefer the retrieved context over conversation history for factual answers."

VALIDATION_PROMPT = "You are given a STATEMENT and a CONTEXT of retrieved passages from the user's knowledge base. Check if the statement is consistent with, contradicted by, or not covered by the context. Respond ONLY with a JSON object with these exact keys: `verdict` (one of: `supported`, `contradicted`, `not_found`), `confidence` (`high` or `low`), `explanation` (why), `suggestion` (corrected version if contradicted, otherwise empty string)."

QUIZ_PROMPT = "generate exactly N questions based on the provided text, respond ONLY with a JSON array. Each item must have: `question` (the question text), `type` (one of: `mcq`, `truefalse`), `options` (list of 4 strings for MCQ, `[\"True\", \"False\"]` for T/F), `correct` (the correct answer — must exactly match one of the options), `explanation` (why it's correct). FORMATTING RULES: For truefalse questions, the question MUST be a declarative statement that can be judged True or False (e.g. 'The sky is blue.'). NEVER phrase truefalse questions as 'what', 'which', 'how', or 'who' questions. For mcq questions, provide exactly 4 distinct answer options and phrase the question naturally. CRITICAL: The provided text is the SOLE source of truth. All correct answers MUST come directly from what the text states, even if the text contradicts common knowledge or real-world facts. You are testing the student's knowledge of THIS text, not general knowledge. Never override or correct the text's claims with your own knowledge."

QUIZ_GRADE_PROMPT = "Compare the student's answer to the provided correct answer. They don't need to match word-for-word — judge whether the student's answer conveys the same meaning as the correct answer. CRITICAL: The provided correct answer is the SOLE source of truth. Do NOT use your own knowledge to override it. Even if the correct answer seems factually wrong by real-world standards, grade the student's answer strictly against the provided correct answer. If the student's answer matches the provided correct answer, mark it correct. Respond ONLY with a JSON object: `correct` (true/false), `feedback` (one sentence explaining why)."

COMPARISON_PROMPT = "given two lists of claims from two different documents, identify any claims that directly contradict each other. Respond ONLY with a JSON array. Each item must have: `claim_a`, `claim_b`, `explanation`."

SUMMARY_PROMPT= "summarize the following content about the given topic in clear, concise prose. Use only the provided content, do not add external information."

CLAIMS_EXTRACTION_PROMPT = "read the following text and extract a list of clear, specific factual claims. Respond ONLY with a JSON array of strings."