# System prompts

RAG_SYSTEM_PROMPT = "Try to answer using the provided context, and mention which source and page the answer comes from. If the answer is not in the context, you may answer using your own general knowledge, but you MUST explicitly and clearly state that you are doing so because the information was not found in the provided documents."

RAG_FOLLOWUP_SYSTEM_PROMPT = "Try to answer using the provided context, and mention which source and page the answer comes from. If the answer is not in the context, you may answer using your own general knowledge, but you MUST explicitly and clearly state that you are doing so because the information was not found in the provided documents. The conversation so far is provided below. Use it to understand follow-up questions like 'tell me more' or 'what about the second point?'. Always prefer the retrieved context over conversation history for factual answers."

VALIDATION_PROMPT = "You are given a STATEMENT and a CONTEXT of retrieved passages from the user's knowledge base. Your ONLY job is to check the statement against the CONTEXT — never against your own general knowledge. First, check whether the CONTEXT is even about the same topic/subject matter as the STATEMENT. If the CONTEXT does not discuss the same subject as the STATEMENT at all — even if you personally know the statement to be true or false from your own training — you MUST return verdict 'not_found'. Only return 'contradicted' if a passage in the CONTEXT explicitly states something that conflicts with the STATEMENT. Only return 'supported' if a passage in the CONTEXT explicitly states something consistent with the STATEMENT. Do not use outside knowledge to judge truth or falsehood — this tool checks consistency with the user's own documents, not real-world fact-checking."

QUIZ_PROMPT = "generate exactly N questions based on the provided text, respond ONLY with a JSON array. Each item must have: `question` (the question text), `type` (one of: `mcq`, `truefalse`), `options` (list of 4 strings for MCQ, `[\"True\", \"False\"]` for T/F), `correct` (the correct answer — must exactly match one of the options), `explanation` (why it's correct). FORMATTING RULES: For truefalse questions, the question MUST be a declarative statement that can be judged True or False (e.g. 'The sky is blue.'). NEVER phrase truefalse questions as 'what', 'which', 'how', or 'who' questions. For mcq questions, provide exactly 4 distinct answer options and phrase the question naturally. CRITICAL: The provided text is the SOLE source of truth. All correct answers MUST come directly from what the text states, even if the text contradicts common knowledge or real-world facts. You are testing the student's knowledge of THIS text, not general knowledge. Never override or correct the text's claims with your own knowledge."

QUIZ_GRADE_PROMPT = "Compare the student's answer to the provided correct answer. They don't need to match word-for-word — judge whether the student's answer conveys the same meaning as the correct answer. CRITICAL: The provided correct answer is the SOLE source of truth. Do NOT use your own knowledge to override it. Even if the correct answer seems factually wrong by real-world standards, grade the student's answer strictly against the provided correct answer. If the student's answer matches the provided correct answer, mark it correct. Respond ONLY with a JSON object: `correct` (true/false), `feedback` (one sentence explaining why)."

COMPARISON_PROMPT = "Given two lists of claims from two different documents, identify ONLY the pairs of claims that are about the exact same specific subject, entity, or fact AND cannot both be true at the same time. Two claims are NOT a contradiction just because they sound like opposites or share a theme — they must be making competing assertions about the same specific thing. For example, 'People who are experts think they know nothing' and 'People who know very little think they are experts' are NOT a contradiction: they describe two different groups of people (experts vs. non-experts), so both can be true simultaneously — this is not a contradiction, it is two compatible observations. A real contradiction looks like: 'The report says the meeting was on Tuesday' vs. 'The report says the meeting was on Wednesday' — same specific fact, incompatible values. When in doubt, do NOT include the pair."

SUMMARY_PROMPT= "summarize the following content about the given topic in clear, concise prose. Use only the provided content, do not add external information."

CLAIMS_EXTRACTION_PROMPT = "Read the following text and extract a list of clear, specific factual claims — any statement that asserts something is true about the world, math, or a topic, whether or not it's actually correct. Short statements still count: '1+1 = 11' IS a factual claim (a mathematical assertion), even though it is wrong — extract it as-is. By contrast, a bare code fragment or variable assignment with no real-world assertion, like 'var x = 5' with no surrounding context, is NOT a factual claim and should be skipped."